const mongoose = require('mongoose');

const binSchema = new mongoose.Schema({
  binId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook if not provided
    unique: true,
    trim: true
  },
  location: {
    type: String,
    required: [true, 'Location is required'],
    trim: true
  },
  zone: {
    type: String,
    required: [true, 'Zone is required'],
    enum: ['Zone A', 'Zone B', 'Zone C', 'Zone D']
  },
  binType: {
    type: String,
    required: [true, 'Bin type is required'],
    enum: ['General Waste', 'Recyclable', 'Organic', 'Hazardous']
  },
  capacity: {
    type: Number,
    required: [true, 'Capacity is required'],
    min: [1, 'Capacity must be at least 1 kg']
  },
  status: {
    type: String,
    enum: ['active', 'inactive', 'maintenance', 'full'],
    default: 'active'
  },
  fillLevel: {
    type: Number,
    min: 0,
    max: 100,
    default: 0
  },
  weight: {
    type: Number,
    default: 0,
    min: 0
  },
  coordinates: {
    lat: {
      type: Number,
      required: false,
      default: null
    },
    lng: {
      type: Number,
      required: false,
      default: null
    }
  },
  registrationDate: {
    type: Date,
    default: Date.now
  },
  lastCollection: {
    type: Date
  },
  notes: {
    type: String,
    maxlength: 500
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
    comment: 'Reference to resident owner if bin is owned by a resident'
  },
  latestCollection: {
    collectedAt: {
      type: Date
    },
    collectedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      comment: 'Reference to collector who collected the bin'
    },
    collectorName: {
      type: String
    },
    weight: {
      type: Number,
      min: 0,
      comment: 'Weight collected in kg'
    },
    fillLevelAtCollection: {
      type: Number,
      min: 0,
      max: 100
    }
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Pre-save hook to update timestamp and generate binId
binSchema.pre('save', async function(next) {
  // Update timestamp
  this.updatedAt = Date.now();
  
  // Generate unique binId if not provided
  if (!this.binId) {
    try {
      const count = await this.constructor.countDocuments();
      this.binId = `BIN${String(count + 1).padStart(4, '0')}`;
      console.log('Auto-generated binId:', this.binId);
    } catch (error) {
      console.error('Error generating binId:', error);
      return next(error);
    }
  }
  
  next();
});

// Virtual for checking if bin is nearly full
binSchema.virtual('isNearlyFull').get(function() {
  return this.fillLevel >= 80;
});

// Virtual for checking if bin needs collection
binSchema.virtual('needsCollection').get(function() {
  return this.fillLevel >= 85 || this.status === 'full';
});

// Enable virtuals in JSON
binSchema.set('toJSON', { virtuals: true });
binSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('Bin', binSchema);
